title: TARHINI
description: A Data Science Student
author: https://github.com/husseintarhini168/Bussiness_Card/releases/download/v1.14/card.pdf
avatar: logo.png
email: hussein.tarhini.etu@lille-univ.fr
website: https://github.com/husseintarhini168/Bussiness_Card/releases/download/v1.14/card.pdf

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Hussein TARHINI
  links:
    - https://github.com/husseintarhini168/Bussiness_Card/releases/download/v1.14/card.pdf
    - https://www.facebook.com/husseintarhini
    - https://github.com/husseintarhini
      
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
